robot:
  qq:
    type: "qq"
    user: 123456789
    host: "127.0.0.1:8094"
service:
  pusher:
    app_id: ""
    key: ""
    secret: ""
    cluster: "ap1"
http_api:
  host: "0.0.0.0"
  port: 8902
  tokens:
    test: abc
channel_config_path: "./channels"
debug: false